routes/ingredients.py
# Importar flask y otros metodos
from flask import Blueprint, render_template, request, redirect, url_for, flash

# Importar mi modelo
from models.Modelos import Ingrediente

# Conexion a la bd
from utils.db import db

ingredients = Blueprint("ingredients", __name__)

@ingredients.route("/")
def home():
    return render_template("index.html")

@ingredients.route("/listarIngrediente")
def consultarIngrediente():
    ingredients = Ingrediente.query.all()
    return render_template("ingrediente/Consultar_Ingrediente.html", ingredients=ingredients)


@ingredients.route("/registrarIngrediente")
def capturarIngrediente():
    return render_template("ingrediente/RegistrarIngrediente.html")


@ingredients.route("/registrarIngredient", methods=["POST"])
def registrarIngrediente():
    nombre = request.form["nombre"]
    descripcion = request.form["descripcion"]
    tipoSabor = request.form["tipoSabor"]
    categoria = request.form["categoria"]

    nuevoIngrediente = Ingrediente(nombre, descripcion, tipoSabor, categoria)

    db.session.add(nuevoIngrediente)
    db.session.commit()

    return redirect(url_for("ingredients.consultarIngrediente"))


@ingredients.route("/actualizarIngrediente/<codigoIngrediente>", methods=["POST", "GET"])
def actualizarIngrediente(codigoIngrediente):

    ingrediente = Ingrediente.query.get(codigoIngrediente)

    if request.method == "POST":
        ingrediente.nombreIngrediente = request.form["nombre"]
        ingrediente.descripcionIngrediente = request.form["descripcion"]
        ingrediente.tipoSaborIngrediente = request.form["tipoSabor"]
        ingrediente.categoriaIngrediente = request.form["categoria"]

        db.session.commit()
        
        return redirect(url_for("ingredients.consultarIngrediente"))

    return render_template("ingrediente/ActualizarIngrediente.html", ingrediente=ingrediente)


@ingredients.route("/eliminar/<codigoIngrediente>")
def eliminarIngrediente(codigoIngrediente):
    ingredient = Ingrediente.query.get(codigoIngrediente)

    db.session.delete(ingredient)
    db.session.commit()

    return redirect(url_for("ingredients.consultarIngrediente"))

templates/ingrediente/ActualizarIngrediente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Ingrediente</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <form action="/actualizarIngrediente/{{ ingrediente.codigoIngrediente }}" method="POST" class="login-form">
            <img src="{{url_for('static',filename='img/logo2.jpg')}} "  >
            <!--<img src="../../Assets/imagene/img/logo2.jpg" height="150px" width="150px" >-->
            <br><br>
            <label for="">Nombre del ingrediente</label>
            <input type="text" name="nombre" value="{{ ingrediente.nombreIngrediente }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Descripción del plato</label>
            <input type="text" name="descripcion" value="{{ ingrediente.descripcionIngrediente }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{7,}" required/>
            <label for="">Tipo sabor del ingrediente</label>
            <input type="text" name="tipoSabor" value="{{ ingrediente.tipoSaborIngrediente }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Categoría del ingrediente</label>
            <input type="text" name="categoria" value="{{ ingrediente.categoriaIngrediente }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <br>
            <button>Actualizar</button>
          </form>
        </div>
      </div>
</body>
</html>

templates/ingrediente/Consultar_Ingrediente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static',filename='img/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/estilos.css')}}">
    <title>Consultar Ingrediente</title>
</head>
<body>
    <table>
      <div class="logo-container">
        <img class="logo" src="{{url_for('static',filename='img/logo2.jpg')}} ">
      </div>
        <thead>
            <tr>
              <th>Código </th>
              <th>Nombre</th>
              <th>Descripción</th>
              <th>Tipo Sabor</th>
              <th>Categoria</th>
              <th></th>
              <th></th>
            </tr>
        </thead>
        {% for ingredient in ingredients %}
        <tbody>
            <tr>
                <td>{{ ingredient.codigoIngrediente }}</td>
                <td>{{ ingredient.nombreIngrediente }}</td>
                <td>{{ ingredient.descripcionIngrediente }}</td>
                <td>{{ ingredient.tipoSaborIngrediente }}</td>
                <td>{{ ingredient.categoriaIngrediente }}</td>
                <td>
                  <a href="{{ url_for('ingredients.actualizarIngrediente', codigoIngrediente=ingredient.codigoIngrediente) }}" class="boton">Actualizar</a>
                </td>
                <td>
                  <a href="{{ url_for('ingredients.eliminarIngrediente', codigoIngrediente=ingredient.codigoIngrediente) }}" class="boton boton-rojo">Eliminar</a>
                </td> 
            </tr>
        </tbody>
        {% endfor %}
    </table>
</body>
</html>

templates/ingrediente/RegistrarIngrediente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Ingrediente</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <form action="/registrarIngredient" method="POST" class="login-form">
            <img src="{{url_for('static',filename='img/logo2.jpg')}} "  >
            <br><br>
            <label for="">Nombre del ingrediente</label>
            <input type="text" name="nombre" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Descripción del plato</label>
            <input type="text" name="descripcion" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{7,}" required/>
            <label for="">Tipo sabor del ingrediente</label>
            <input type="text" name="tipoSabor" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Categoría del ingrediente</label>
            <input type="text" name="categoria" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <br>
            <button>Registrar</button>
          </form>
        </div>
      </div>
</body>
</html>