routes/login.py
# Importar flask y otros metodos
from flask import Blueprint, render_template, request, redirect, url_for
#Importar werkzeug para encriptar la contraseña
from werkzeug.security import generate_password_hash, check_password_hash

# Importar mi modelo
from models.Modelos import Usuario

# Conexion a la bd
from utils.db import db

Login = Blueprint("login", __name__)

@Login.route('/registrar')
def registrar():
    return render_template('Login/Registrar.html')

@Login.route('/crearCuenta')
def crearCuenta():
    return render_template('Login/Registrar.html')

@Login.route('/iniciarSesion')
def iniciarSesion():
    return render_template('Login/login.html')

@Login.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        # Obtener los datos del formulario de inicio de sesión
        correo = request.form['correo']
        password = request.form['password']

        # Realizar la lógica de autenticación aquí (por ejemplo, consultar la base de datos)
        user = Usuario.query.filter_by(correoUsuario=correo, passwordUsuario=password).first()

        if user:
            # Autenticación exitosa, redirigir a una página de inicio o dashboard
            return render_template('plato/Consultar_Plato.html')
        
        else:
             return render_template('Login/login.html', error = 'Credenciales incorrectas')

    return redirect(url_for('login.iniciarSesion'))

templates/login/Registrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrate esturio</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/imge/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <form method="POST" class="login-form">
            <img src= "{{url_for('static',filename='img/imge/logo2.jpg')}}" height="150px" width="150px" >
            </br>
            </br> 
            <label for="">Correo Electrónico</label>
            <input type="text" name="correo"/>
            <label for="">Contraseña</label>
            <input type="password" name="password"/>
            <label for="">Confirme contrasña</label>
            <input type="password" name="password"/>
            <br>
            <button><a href="{{ url_for('login.login') }}"style="color: antiquewhite;">Registrate</a></button>
          </form>
        </div>
      </div>
</body>
</html>

templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/imge/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <form action="/login" method="POST" class="login-form">
            <img src= "{{url_for('static',filename='img/imge/logo2.jpg')}}" height="150px" width="150px" >
            <br><br>
            <label for="">Usuario</label>
            <input name="correo" type="text"/>
            <label for="">Contraseña</label>
            <input name="password" type="password"/>
            <br>
            <button type="submit"><a href=""style="color: antiquewhite;">ingresar</a></button>
            <p><a href="{{ url_for('login.registrar') }}">Registrate</a></p>
          </form>
        </div>
      </div>
</body>
</html>