routes/plates.py
# Importar flask y otros metodos
from flask import Blueprint, render_template, request, redirect, url_for, flash

# Importar mi modelo
from models.Modelos import Plato

# Conexion a la bd
from utils.db import db

plates = Blueprint("plates", __name__)

@plates.route("/")
def home():
    return render_template("index.html")

@plates.route("/listarPlato")
def consultarPlato():
    plates = Plato.query.all()
    return render_template("plato/Consultar_Plato.html", plates=plates)


@plates.route("/registrarPlato")
def capturarPlato():
    return render_template("plato/RegistrarPlato.html")


@plates.route("/registrarPlate", methods=["POST"])
def registrarPlato():
    nombre = request.form["nombre"]
    descripcion = request.form["descripcion"]
    precio = request.form["precio"]

    nombre = request.form.get("nombre")
    descripcion = request.form.get("descripcion")
    precio = request.form.get("precio")

    nuevoPlato = Plato(nombre, descripcion, precio)

    db.session.add(nuevoPlato)
    db.session.commit()

    return redirect(url_for("plates.consultarPlato"))


@plates.route("/actualizarPlato/<codigoPlato>", methods=["POST", "GET"])
def actualizarPlato(codigoPlato):

    plate = Plato.query.get(codigoPlato)

    if request.method == "POST":
        plate.nombrePlato = request.form["nombre"]
        plate.descripcionPlato = request.form["descripcion"]
        plate.precioPlato = request.form["precio"]

        db.session.commit()
        
        return redirect(url_for("plates.consultarPlato"))

    return render_template("plato/ActualizarPlato.html", plate=plate)


@plates.route("/eliminarPlato/<codigoPlato>")
def eliminarPlato(codigoPlato):
    plate = Plato.query.get(codigoPlato)

    db.session.delete(plate)
    db.session.commit()

    return redirect(url_for("plates.consultarPlato"))

templates/plato/ActualizarPlato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Plato</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <form action="/actualizarPlato/{{ plate.codigoPlato }}" method="POST" class="login-form">
            <img src="{{url_for('static',filename='img/logo2.jpg')}} "  >
            <!--<img src="../../Assets/imagene/img/logo2.jpg" height="150px" width="150px" >-->
            <br><br>
            <label for="">Nombre del plato</label>
            <input type="text" name="nombre" value="{{ plate.nombrePlato }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}"  required/>
            <label for="">Descripción del plato</label>
            <input type="text" name="descripcion" value="{{ plate.descripcionPlato }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{10,}" required/>
            <label for="">Precio del plato</label>
            <input type="number" name="precio" value="{{ plate.precioPlato }}" min="5000" step="1" required/>
            <br>
            <button>Actualizar</button>
          </form>
        </div>
      </div>
</body>
</html>

templates/plato/Consultar_Plato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static',filename='img/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/estilos.css')}}">
    <title>Consultar Plato</title>
</head>
<body>
    <table>
      <div class="logo-container">
        <img class="logo" src="{{url_for('static',filename='img/logo2.jpg')}} ">
      </div>
        <thead>
            <tr>
              <th>Código </th>
              <th>Nombre</th>
              <th>Descripción</th>
              <th>Precio</th>
              <th></th>
              <th></th>
            </tr>
        </thead>
        {% for plate in plates %}
        <tbody>
            <tr>
                <td>{{ plate.codigoPlato }}</td>
                <td>{{ plate.nombrePlato }}</td>
                <td>{{ plate.descripcionPlato }}</td>
                <td>{{ plate.precioPlato }}</td>
                <td>
                  <a href="{{ url_for('plates.actualizarPlato', codigoPlato=plate.codigoPlato) }}" class="boton">Actualizar</a>
                </td>
                <td>
                  <a href="{{ url_for('plates.eliminarPlato', codigoPlato=plate.codigoPlato) }}" class="boton boton-rojo">Eliminar</a>
                </td> 
            </tr>
        </tbody>
        {% endfor %}
    </table>
</body>
</html>

templates/plato/RegistrarPlato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Plato</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <form id="registrarPlato" action="/registrarPlate" method="POST" class="login-form">
            <img src="{{url_for('static',filename='img/logo2.jpg')}} "  >
            <br><br>
            <label for="">Nombre del plato</label>
            <input type="text" name="nombre" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Descripción del plato</label>
            <input type="text" name="descripcion" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{10,}" required/>
            <label for="">Precio del plato</label>
            <input type="number" name="precio" min="5000" step="1" required/>
            <br>
            <button type="submit">Registrar</button>
          </form>
        </div>
      </div>  
  </body>
</html>